services:
  csohelper-backend-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - ./storage/pgdata/:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  csohelper-backend-app:
    build: .
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - ./storage/backend/:/app/storage/
    depends_on:
      csohelper-backend-postgres:
        condition: service_healthy
    ports:
      - 8000:8000